keybinds = {'interaction_main': 'e',
            'interaction_menu': 'q',
            'player_forward': 'w',
            'player_backward': 's',
            'player_right': 'd',
            'player_left': 'a',
            'player_jump': 'space',
            'player_sneak': 'shift',
            'player_swim': 'control-l',
            'weapon_melee': 'f',
            'weapon_sidearm': '1',
            'weapon_main': '2',
            'weapon_shoot': 'left mouse down',
            'weapon_aim': 'right mouse down',
            'weapon_reload': 'e',
            'weapon_throw_ammo': 't',
            'vehicle_brake': 'space',
            'vehicle_accelerate': 'z',
            'vehicle_slowdown': 's',
            'vehicle_eject': 'n',
            'vehicle_destroy': 'e',
            'advanced_options': 'f10',
            }